name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install test tools.
      run: go get github.com/tebeka/go2xunit
    - name: Run tests.
      run: go test --coverprofile coverage.out -v ./... 2>&1 | go2xunit -output test.xunit
    - name: Generate coverage report.
      run: go tool cover -html=coverage.out -o coverage.html
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test.xunit
    - name: Save artifacts.
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Coverage report.
        path: ./coverage.html

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate format report.
      run: gofmt -d .
    - name: Run format again (so job will error if format issues found).
      run: test -z $(gofmt -l .)

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
